name: Build AutoCAD Plugin
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build DLL
        run: msbuild CONT2BLK.csproj /p:Configuration=Release
